// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package com.digitalasset.canton.topology.admin.v30;

import "google/protobuf/timestamp.proto";

// Topology transaction collection used during bootstrapping of synchronizer nodes and on the admin API
message TopologyTransactions {
  message Item {
    google.protobuf.Timestamp sequenced = 4;
    google.protobuf.Timestamp valid_from = 1;
    google.protobuf.Timestamp valid_until = 2;

    // Versioned signed topology transactions serialized as byte-strings.
    bytes transaction = 3;

    optional string rejection_reason = 5;
  }

  repeated Item items = 1;
}

message Synchronizer {
  oneof kind {
    string id = 1;
    string physical_id = 2;
  }
}

message StoreId {
  message Authorized {}

  message Temporary {
    string name = 1;
  }

  oneof store {
    Authorized authorized = 1;
    Synchronizer synchronizer = 2;
    Temporary temporary = 3;
  }
}
